### ISSUE TITLE
Prototype circuit design

### ISSUE THREAD

**Issue by jjholt** [jjholt/Braille-research#16]
Outline the veroboard design, how it differs from the finished product and how we ended up with something larger than a breadboard.

One reason was because the wiring of the veroboard made us put the components side-by-side. In both the PCB and breadboard designs we have components really tightly packed together.

Some other differences are trivial, like the PCB using a CPU and SMD components, like the Bluetooth, all the resistors, etc. The veroboard uses a development board + through-hole components.

**Comment by NZavas** [comment]
Looks really good. I will implement what i need
